# Generated by Django 5.0.1 on 2024-01-18 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_article', models.CharField(max_length=100, verbose_name='Titre Article')),
                ('synopsis_article', models.CharField(max_length=180, verbose_name='Synopsis Article')),
                ('auteur_article', models.CharField(max_length=60, verbose_name='Auteur Article')),
                ('date_creation_article', models.DateTimeField(auto_now_add=True, verbose_name='Date Article')),
                ('contenu_article', models.TextField(verbose_name='Contenu Article')),
                ('categorie_article', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='blog.categorie', verbose_name='Categorie Article')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
